version: "3.6"
## Service Definitions
services:
  ## Klippy Services
  ##
  klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    depends_on:
      init:
        condition: service_completed_successfully
    command: -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer.cfg -l printer_data/logs/klippy.log
    volumes:
      - /dev:/dev
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs

  ## WebApi
  ##
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    depends_on:
      init:
        condition: service_completed_successfully
      klipper:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config:/opt/printer_data/config
    labels:
      traefik.enable: true
      traefik.http.services.moonraker.loadbalancer.server.port: 7125

  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.fluidd.loadbalancer.server.port: 80

  ## Config dir needs to be writable by uid/gid 1000
  ## This container sets the right permissions and exits
  init:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config
    volumes:
      - .:/prind
    labels:
      org.prind.service: init

networks:
  default:
    name: traefik
    external: true

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
